CXX = c++
CXXFLAG = -Wall -Wextra -Werror -std=c++98

NAME = polymorphism

SRC = main.cpp \
			Animal.cpp \
			Cat.cpp \
			Dog.cpp \
			WrongCat.cpp \
			WrongAnimal.cpp
OBJ = $(SRC:.cpp=.o)

all : $(NAME)

$(NAME) : $(OBJ)
	$(CXX) $(CXXFLAG) $^ -o $@

%.o : %.cpp
	$(CXX) $(CXXFLAG) -c $< -o $@

clean : 
	rm -f $(OBJ)

fclean : clean
	rm -f $(NAME)

re : fclean all

.PHONY: all clean fclean re